### ISSUE TITLE
Update Meilenstein 0.1.0

### ISSUE THREAD

**Issue by novawarpN7** [DLVC-Project/MonoRepo#10]
@lordtulek: Hier versuchen wir den ersten Meilenstein zu definieren. Bitte die Liste ergänzen, was dir an Funktionalität noch für den Start wichtig ist.

**Ziel: es soll eine bereits nutzbare Version der Software vorliegen.**

- [ ] Design der Startseite ist definiert (s. #12)
- [ ] Software hat einen guten Namen --> **Ho Valalor**
- [ ] Spieler haben ausreichend Attributte um in den Kampf zu ziehen (s. #9)
- [ ] Gegner haben ausreichend Attributte um in den Kampf zu ziehen (s. #11)
- [ ] Software unterstützt den Kampfablauf (s. #13)
